# Python language server
[[language]]
name = "python"
auto-format = true
formatter = { command = "black", args = ["--quiet", "-"] }
language-servers = ["pylsp"]

[language-server.pylsp]
command = "pylsp"

# Rust language server
[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
formatter = { command = "rustfmt" }

[language-server.rust-analyzer]
command = "rust-analyzer"

# Nix with nil instead of nixd
[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }
language-servers = ["nil"]

[language-server.nil]
command = "nil"
[language-server.nil.config]
formatting = { command = [ "nixpkgs-fmt" ] }
